
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function Page() {
  const filename = './content.mdx'
  const Content = await import(__dirname + '/' + filename)

  return (
    <div>
      <h1>Page</h1>
      <p>This is the page.</p>

      <Content />

      <Link href="/broken">Home</Link>
    </div>
  );
}